### ISSUE TITLE
启动集群PD启动报错

### ISSUE THREAD

**Issue by DarrenZhao** [pingcap/tidb-ansible#787] opened 2019-06-21 08:15 UTC
ERROR MESSAGE SUMMARY ***********************************************************************************************************************************
[10.162.0.200]: Ansible FAILED! => playbook: start.yml; TASK: wait for PD up; message: {"changed": false, "module_stderr": "Shared connection to 10.162.0.200 closed.\r\n", "module_stdout": "ln: failed to create symbolic link ‘/opt/soft/java’: Permission denied\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_kWnigy/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_kWnigy/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 0}

1、tidb用户加入了sudoers，而且安装前检查都是通过的

**Comment by liubo0127** [comment] 2019-07-12 02:39
看起来像是环境问题，10.162.0.200 节点的 pd 日志有什么异常吗

**Comment by liubo0127** [comment] 2019-07-25 06:34
I will close this issue. If the problem is not resolved, you can reopen it.

**Closed by liubo0127** 2019-07-25 06:34 UTC
